package org.smoothbuild.parse.ast;

/**
 * Specified place from which definition is taken.
 */
public enum DefinitionKind {
  /**
   * Defined in Smooth source code.
   */
  SOURCE,

  /**
   * Defined in native code (java language).
   */
  NATIVE,

  /**
   * Autogenerated.
   */
  GENERATED
}
